on:
  - push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: cloud-cli/workflows/.github/workflows/docker-ghcr-build.yml@main
    permissions:
      contents: read
      packages: write
    with:
      name: aifn-run/aifn-run
      baseImage: cloud-cli/node:latest
      defaultBranch: main
      withSha: false
      withTag: true
      type: vite